# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stock.proto',
  package='python_example.stock',
  syntax='proto3',
  serialized_options=b'\n\017stock.generatedP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstock.proto\x12\x14python_example.stock\"\x13\n\x11GetProductRequest\"%\n\x14\x43reateProductRequest\x12\r\n\x05price\x18\x01 \x01(\x05\"\x16\n\x14\x44\x65leteProductRequest\"(\n\x16\x41\x64\x64ProductStockRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"-\n\x1bSubtractProductStockRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"\xad\x03\n\x0cStockRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12>\n\x0bget_product\x18\x03 \x01(\x0b\x32\'.python_example.stock.GetProductRequestH\x00\x12\x44\n\x0e\x63reate_product\x18\x04 \x01(\x0b\x32*.python_example.stock.CreateProductRequestH\x00\x12\x44\n\x0e\x64\x65lete_product\x18\x05 \x01(\x0b\x32*.python_example.stock.DeleteProductRequestH\x00\x12I\n\x11\x61\x64\x64_product_stock\x18\x06 \x01(\x0b\x32,.python_example.stock.AddProductStockRequestH\x00\x12S\n\x16subtract_product_stock\x18\x07 \x01(\x0b\x32\x31.python_example.stock.SubtractProductStockRequestH\x00\x42\t\n\x07message\"\x9e\x01\n\rStockResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x12\x10\n\x06string\x18\x04 \x01(\tH\x00\x12\x33\n\x05state\x18\x05 \x01(\x0b\x32\".python_example.stock.ProductStateH\x00\x42\t\n\x07payload\"=\n\x0cProductState\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x05\x42\x13\n\x0fstock.generatedP\x01\x62\x06proto3'
)




_GETPRODUCTREQUEST = _descriptor.Descriptor(
  name='GetProductRequest',
  full_name='python_example.stock.GetProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=56,
)


_CREATEPRODUCTREQUEST = _descriptor.Descriptor(
  name='CreateProductRequest',
  full_name='python_example.stock.CreateProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='python_example.stock.CreateProductRequest.price', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=95,
)


_DELETEPRODUCTREQUEST = _descriptor.Descriptor(
  name='DeleteProductRequest',
  full_name='python_example.stock.DeleteProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=119,
)


_ADDPRODUCTSTOCKREQUEST = _descriptor.Descriptor(
  name='AddProductStockRequest',
  full_name='python_example.stock.AddProductStockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='python_example.stock.AddProductStockRequest.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=161,
)


_SUBTRACTPRODUCTSTOCKREQUEST = _descriptor.Descriptor(
  name='SubtractProductStockRequest',
  full_name='python_example.stock.SubtractProductStockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='python_example.stock.SubtractProductStockRequest.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=208,
)


_STOCKREQUEST = _descriptor.Descriptor(
  name='StockRequest',
  full_name='python_example.stock.StockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='python_example.stock.StockRequest.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='python_example.stock.StockRequest.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_product', full_name='python_example.stock.StockRequest.get_product', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create_product', full_name='python_example.stock.StockRequest.create_product', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete_product', full_name='python_example.stock.StockRequest.delete_product', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_product_stock', full_name='python_example.stock.StockRequest.add_product_stock', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subtract_product_stock', full_name='python_example.stock.StockRequest.subtract_product_stock', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='python_example.stock.StockRequest.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=211,
  serialized_end=640,
)


_STOCKRESPONSE = _descriptor.Descriptor(
  name='StockResponse',
  full_name='python_example.stock.StockResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='python_example.stock.StockResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='python_example.stock.StockResponse.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='python_example.stock.StockResponse.status_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string', full_name='python_example.stock.StockResponse.string', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='python_example.stock.StockResponse.state', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='python_example.stock.StockResponse.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=643,
  serialized_end=801,
)


_PRODUCTSTATE = _descriptor.Descriptor(
  name='ProductState',
  full_name='python_example.stock.ProductState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='python_example.stock.ProductState.deleted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stock', full_name='python_example.stock.ProductState.stock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='python_example.stock.ProductState.price', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=803,
  serialized_end=864,
)

_STOCKREQUEST.fields_by_name['get_product'].message_type = _GETPRODUCTREQUEST
_STOCKREQUEST.fields_by_name['create_product'].message_type = _CREATEPRODUCTREQUEST
_STOCKREQUEST.fields_by_name['delete_product'].message_type = _DELETEPRODUCTREQUEST
_STOCKREQUEST.fields_by_name['add_product_stock'].message_type = _ADDPRODUCTSTOCKREQUEST
_STOCKREQUEST.fields_by_name['subtract_product_stock'].message_type = _SUBTRACTPRODUCTSTOCKREQUEST
_STOCKREQUEST.oneofs_by_name['message'].fields.append(
  _STOCKREQUEST.fields_by_name['get_product'])
_STOCKREQUEST.fields_by_name['get_product'].containing_oneof = _STOCKREQUEST.oneofs_by_name['message']
_STOCKREQUEST.oneofs_by_name['message'].fields.append(
  _STOCKREQUEST.fields_by_name['create_product'])
_STOCKREQUEST.fields_by_name['create_product'].containing_oneof = _STOCKREQUEST.oneofs_by_name['message']
_STOCKREQUEST.oneofs_by_name['message'].fields.append(
  _STOCKREQUEST.fields_by_name['delete_product'])
_STOCKREQUEST.fields_by_name['delete_product'].containing_oneof = _STOCKREQUEST.oneofs_by_name['message']
_STOCKREQUEST.oneofs_by_name['message'].fields.append(
  _STOCKREQUEST.fields_by_name['add_product_stock'])
_STOCKREQUEST.fields_by_name['add_product_stock'].containing_oneof = _STOCKREQUEST.oneofs_by_name['message']
_STOCKREQUEST.oneofs_by_name['message'].fields.append(
  _STOCKREQUEST.fields_by_name['subtract_product_stock'])
_STOCKREQUEST.fields_by_name['subtract_product_stock'].containing_oneof = _STOCKREQUEST.oneofs_by_name['message']
_STOCKRESPONSE.fields_by_name['state'].message_type = _PRODUCTSTATE
_STOCKRESPONSE.oneofs_by_name['payload'].fields.append(
  _STOCKRESPONSE.fields_by_name['string'])
_STOCKRESPONSE.fields_by_name['string'].containing_oneof = _STOCKRESPONSE.oneofs_by_name['payload']
_STOCKRESPONSE.oneofs_by_name['payload'].fields.append(
  _STOCKRESPONSE.fields_by_name['state'])
_STOCKRESPONSE.fields_by_name['state'].containing_oneof = _STOCKRESPONSE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['GetProductRequest'] = _GETPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['CreateProductRequest'] = _CREATEPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['DeleteProductRequest'] = _DELETEPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['AddProductStockRequest'] = _ADDPRODUCTSTOCKREQUEST
DESCRIPTOR.message_types_by_name['SubtractProductStockRequest'] = _SUBTRACTPRODUCTSTOCKREQUEST
DESCRIPTOR.message_types_by_name['StockRequest'] = _STOCKREQUEST
DESCRIPTOR.message_types_by_name['StockResponse'] = _STOCKRESPONSE
DESCRIPTOR.message_types_by_name['ProductState'] = _PRODUCTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetProductRequest = _reflection.GeneratedProtocolMessageType('GetProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.GetProductRequest)
  })
_sym_db.RegisterMessage(GetProductRequest)

CreateProductRequest = _reflection.GeneratedProtocolMessageType('CreateProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPRODUCTREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.CreateProductRequest)
  })
_sym_db.RegisterMessage(CreateProductRequest)

DeleteProductRequest = _reflection.GeneratedProtocolMessageType('DeleteProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPRODUCTREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.DeleteProductRequest)
  })
_sym_db.RegisterMessage(DeleteProductRequest)

AddProductStockRequest = _reflection.GeneratedProtocolMessageType('AddProductStockRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDPRODUCTSTOCKREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.AddProductStockRequest)
  })
_sym_db.RegisterMessage(AddProductStockRequest)

SubtractProductStockRequest = _reflection.GeneratedProtocolMessageType('SubtractProductStockRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBTRACTPRODUCTSTOCKREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.SubtractProductStockRequest)
  })
_sym_db.RegisterMessage(SubtractProductStockRequest)

StockRequest = _reflection.GeneratedProtocolMessageType('StockRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOCKREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.StockRequest)
  })
_sym_db.RegisterMessage(StockRequest)

StockResponse = _reflection.GeneratedProtocolMessageType('StockResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOCKRESPONSE,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.StockResponse)
  })
_sym_db.RegisterMessage(StockResponse)

ProductState = _reflection.GeneratedProtocolMessageType('ProductState', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSTATE,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:python_example.stock.ProductState)
  })
_sym_db.RegisterMessage(ProductState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
