# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='python_example.users',
  syntax='proto3',
  serialized_options=b'\n\016user.generatedP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nuser.proto\x12\x14python_example.users\"\x10\n\x0eGetUserRequest\"\x13\n\x11\x43reateUserRequest\"\x13\n\x11\x44\x65leteUserRequest\"&\n\x14\x41\x64\x64UserCreditRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"+\n\x19SubtractUserCreditRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"\x8f\x03\n\x0bUserRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x38\n\x08get_user\x18\x03 \x01(\x0b\x32$.python_example.users.GetUserRequestH\x00\x12>\n\x0b\x63reate_user\x18\x04 \x01(\x0b\x32\'.python_example.users.CreateUserRequestH\x00\x12>\n\x0b\x64\x65lete_user\x18\x05 \x01(\x0b\x32\'.python_example.users.DeleteUserRequestH\x00\x12\x45\n\x0f\x61\x64\x64_user_credit\x18\x06 \x01(\x0b\x32*.python_example.users.AddUserCreditRequestH\x00\x12O\n\x14subtract_user_credit\x18\x07 \x01(\x0b\x32/.python_example.users.SubtractUserCreditRequestH\x00\x42\t\n\x07message\"\x97\x01\n\x0cUserResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x12\x10\n\x06string\x18\x04 \x01(\tH\x00\x12\x30\n\x05state\x18\x05 \x01(\x0b\x32\x1f.python_example.users.UserStateH\x00\x42\t\n\x07payload\",\n\tUserState\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x05\x42\x12\n\x0euser.generatedP\x01\x62\x06proto3'
)




_GETUSERREQUEST = _descriptor.Descriptor(
  name='GetUserRequest',
  full_name='python_example.users.GetUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=52,
)


_CREATEUSERREQUEST = _descriptor.Descriptor(
  name='CreateUserRequest',
  full_name='python_example.users.CreateUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=73,
)


_DELETEUSERREQUEST = _descriptor.Descriptor(
  name='DeleteUserRequest',
  full_name='python_example.users.DeleteUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=94,
)


_ADDUSERCREDITREQUEST = _descriptor.Descriptor(
  name='AddUserCreditRequest',
  full_name='python_example.users.AddUserCreditRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='python_example.users.AddUserCreditRequest.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=134,
)


_SUBTRACTUSERCREDITREQUEST = _descriptor.Descriptor(
  name='SubtractUserCreditRequest',
  full_name='python_example.users.SubtractUserCreditRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='python_example.users.SubtractUserCreditRequest.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=179,
)


_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='python_example.users.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='python_example.users.UserRequest.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='python_example.users.UserRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_user', full_name='python_example.users.UserRequest.get_user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create_user', full_name='python_example.users.UserRequest.create_user', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete_user', full_name='python_example.users.UserRequest.delete_user', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_user_credit', full_name='python_example.users.UserRequest.add_user_credit', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subtract_user_credit', full_name='python_example.users.UserRequest.subtract_user_credit', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='python_example.users.UserRequest.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=182,
  serialized_end=581,
)


_USERRESPONSE = _descriptor.Descriptor(
  name='UserResponse',
  full_name='python_example.users.UserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='python_example.users.UserResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='python_example.users.UserResponse.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='python_example.users.UserResponse.status_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string', full_name='python_example.users.UserResponse.string', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='python_example.users.UserResponse.state', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='python_example.users.UserResponse.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=584,
  serialized_end=735,
)


_USERSTATE = _descriptor.Descriptor(
  name='UserState',
  full_name='python_example.users.UserState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='python_example.users.UserState.deleted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='credit', full_name='python_example.users.UserState.credit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=737,
  serialized_end=781,
)

_USERREQUEST.fields_by_name['get_user'].message_type = _GETUSERREQUEST
_USERREQUEST.fields_by_name['create_user'].message_type = _CREATEUSERREQUEST
_USERREQUEST.fields_by_name['delete_user'].message_type = _DELETEUSERREQUEST
_USERREQUEST.fields_by_name['add_user_credit'].message_type = _ADDUSERCREDITREQUEST
_USERREQUEST.fields_by_name['subtract_user_credit'].message_type = _SUBTRACTUSERCREDITREQUEST
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['get_user'])
_USERREQUEST.fields_by_name['get_user'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['create_user'])
_USERREQUEST.fields_by_name['create_user'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['delete_user'])
_USERREQUEST.fields_by_name['delete_user'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['add_user_credit'])
_USERREQUEST.fields_by_name['add_user_credit'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['subtract_user_credit'])
_USERREQUEST.fields_by_name['subtract_user_credit'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERRESPONSE.fields_by_name['state'].message_type = _USERSTATE
_USERRESPONSE.oneofs_by_name['payload'].fields.append(
  _USERRESPONSE.fields_by_name['string'])
_USERRESPONSE.fields_by_name['string'].containing_oneof = _USERRESPONSE.oneofs_by_name['payload']
_USERRESPONSE.oneofs_by_name['payload'].fields.append(
  _USERRESPONSE.fields_by_name['state'])
_USERRESPONSE.fields_by_name['state'].containing_oneof = _USERRESPONSE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['GetUserRequest'] = _GETUSERREQUEST
DESCRIPTOR.message_types_by_name['CreateUserRequest'] = _CREATEUSERREQUEST
DESCRIPTOR.message_types_by_name['DeleteUserRequest'] = _DELETEUSERREQUEST
DESCRIPTOR.message_types_by_name['AddUserCreditRequest'] = _ADDUSERCREDITREQUEST
DESCRIPTOR.message_types_by_name['SubtractUserCreditRequest'] = _SUBTRACTUSERCREDITREQUEST
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['UserResponse'] = _USERRESPONSE
DESCRIPTOR.message_types_by_name['UserState'] = _USERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetUserRequest = _reflection.GeneratedProtocolMessageType('GetUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.GetUserRequest)
  })
_sym_db.RegisterMessage(GetUserRequest)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

DeleteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.DeleteUserRequest)
  })
_sym_db.RegisterMessage(DeleteUserRequest)

AddUserCreditRequest = _reflection.GeneratedProtocolMessageType('AddUserCreditRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERCREDITREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.AddUserCreditRequest)
  })
_sym_db.RegisterMessage(AddUserCreditRequest)

SubtractUserCreditRequest = _reflection.GeneratedProtocolMessageType('SubtractUserCreditRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBTRACTUSERCREDITREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.SubtractUserCreditRequest)
  })
_sym_db.RegisterMessage(SubtractUserCreditRequest)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

UserState = _reflection.GeneratedProtocolMessageType('UserState', (_message.Message,), {
  'DESCRIPTOR' : _USERSTATE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:python_example.users.UserState)
  })
_sym_db.RegisterMessage(UserState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
