FROM python:3.8.6-alpine3.11

RUN mkdir -p /app
WORKDIR /app

COPY functions/requirements.txt /app
RUN pip install -r requirements.txt

COPY functions/account_function.py /app
COPY protobuf/messages_pb2.py /app

CMD ["gunicorn", "-b", "0.0.0.0:80", "-w 1", "account_function:app"]
