FROM thesis-statefun-python-sdk-base-image:latest

RUN mkdir -p /app
WORKDIR /app

COPY functions/requirements.txt /app
RUN pip install -r requirements.txt

COPY functions/account_function.py /app
COPY protobuf/messages_pb2.py /app
COPY functions/exceptions.py /app

CMD ["gunicorn", "-b", "0.0.0.0:80", "-w 1", "account_function:app"]
