apiVersion: v1
kind: Service
metadata:
  name: stock-gateway
spec:
  type: LoadBalancer
  selector:
    service: stock-gateway
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-gateway
spec:
  selector:
    matchLabels:
      service: stock-gateway
  replicas: 1
  template:
    metadata:
      labels:
        service: stock-gateway
    spec:
      containers:
        - name: stock-gateway
          image: "statefun-tpc-python-example_stock-gateway:latest"
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: KAFKA_BROKER
              value: 'kafka-cluster-kafka-bootstrap:9092'
          resources:
            requests:
              memory: "400Mi"
              cpu: "375m"
            limits:
              memory: "500Mi"
              cpu: "400m"